<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\BookPdf;
use App\Models\Book;
use App\Models\Exam;
use App\Models\Result;
use App\Models\MCQ;
use App\Models\Topic;
use App\Models\LatestTopic;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $this->call('UsersTableSeeder');
        // $this->call('BookPdfSeeder');
        // $this->call('BookSeeder');
        // $this->call('ExamSeeder');
        // $this->call('LatestTopicSeeder');
        // $this->call('MCQSeeder');
        // $this->call('ResultSeeder');
        // $this->call('TopicSeeder');
        BookPdf::insert([
            [
                'book_id' => 1,
                'topic_id' => 1,
                'pdfName' => "sample.pdf",
            ],
            [
                'book_id' => 2,
                'topic_id' => 1,
                'pdfName' => "sample.pdf",
            ],
            [
                'book_id' => 3,
                'topic_id' => 1,
                'pdfName' => "sample.pdf",
            ],
            [
                'book_id' => 3,
                'topic_id' => 2,
                'pdfName' => "sample.pdf",
            ],
        ]);

        Book::insert([
            [
                'bookName' => "Bangla",
            ],
            [
                'bookName' => "English",
            ],
            [
                'bookName' => "Mathmatics",
            ],
            [
                'bookName' => "ICT",
            ],
        ]);

        Exam::insert([
            [
                'examName' => "Model Test 1",
            ],
            [
                'examName' => "Model Test 2",
            ],
            [
                'examName' => "Model Test 3",
            ],
        ]);

        LatestTopic::insert([
            [
                'content' => "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Alias temporibus at inventore odit. Veritatis porro sapiente, suscipit sint ad quos nam fugiat, provident dolorem quis itaque, ipsam doloremque! Quibusdam, debitis.",
            ],
        ]);

        MCQ::insert([
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
            [
                'exam_id' => 1,
                'questionName' => "Question 1",
                'questionDescription' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit error quas commodi ut libero, perferendis, debitis rem quia aliquam, porro odit. Accusantium et quidem laborum quae. Quibusdam sed quae animi!",
                'optionOne' => "answer a",
                'optionTwo' => "answer b",
                'optionThree' => "answer c",
                'optionFour' => "answer d",
                'answer' => "1",
            ],
        ]);

        Result::insert([
            [
                'exam_id' => 1,
                'user_id' => 1,
                'mcq_id' => 1,
                'answer' => 1,
            ],
            [
                'exam_id' => 1,
                'user_id' => 1,
                'mcq_id' => 2,
                'answer' => 4,
            ],
            [
                'exam_id' => 1,
                'user_id' => 1,
                'mcq_id' => 3,
                'answer' => 2,
            ],
        ]);

        Topic::insert([
            [
                'book_id' => 1,
                'topicName' => "topic-1",
                // 'isAdmin' => 1,
                // 'name' => 'Admin',
                // 'image' => null,
                // 'phone' => '01775559622',
                // 'email' => 'admin@futureskyltd.com',
                // 'password' => bcrypt('A@superadmin'),
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'book_id' => 1,
                'topicName' => "topic-2",
            ],
            [
                'book_id' => 2,
                'topicName' => "topic-1",
            ],
            [
                'book_id' => 2,
                'topicName' => "topic-2",
            ],
            [
                'book_id' => 3,
                'topicName' => "topic-1",
            ],
            [
                'book_id' => 3,
                'topicName' => "topic-2",
            ],
        ]);
    }
}
